# Test whether we can link to LLVM installed from apt.llvm.org or Homebrew.
---

name: Test

on: [push, pull_request]

jobs:
  test-macos-llvm-14:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          brew update
          brew install llvm@14
      - name: Test LLVM 14
        run:
          go test -v -tags=llvm14
  test-macos-llvm-15:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          brew update
          brew install llvm@15
      - name: Test LLVM 15
        run:
          go test -v -tags=llvm15
  test-macos-llvm-16:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          brew update
          brew install llvm@16
      - name: Test LLVM 16
        run:
          go test -v -tags=llvm16
      - name: Test default LLVM
        run:
          go test -v
  test-macos-llvm-17:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          brew update
          brew install llvm@17
      - name: Test LLVM 17
        run:
          go test -v -tags=llvm17
  test-linux-llvm-14:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          echo 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main' | sudo tee /etc/apt/sources.list.d/llvm.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install --no-install-recommends llvm-14-dev
      - name: Test LLVM 14
        run:
          go test -v -tags=llvm14
  test-linux-llvm-15:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          echo 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main' | sudo tee /etc/apt/sources.list.d/llvm.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install --no-install-recommends llvm-15-dev
      - name: Test LLVM 15
        run:
          go test -v -tags=llvm15
  test-linux-llvm-16:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          echo 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-16 main' | sudo tee /etc/apt/sources.list.d/llvm.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install --no-install-recommends llvm-16-dev
      - name: Test LLVM 16
        run:
          go test -v -tags=llvm16
      - name: Test default LLVM
        run:
          go test -v
  test-linux-llvm-17:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM
        run: |
          echo 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-17 main' | sudo tee /etc/apt/sources.list.d/llvm.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install --no-install-recommends llvm-17-dev
      - name: Test LLVM 17
        run:
          go test -v -tags=llvm17
